# Generated by Django 5.2.7 on 2025-10-14 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_application_user_resumevariant_application_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='application_url',
            field=models.URLField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='external_id',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
