# Generated by Django 5.2.7 on 2025-10-15 01:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_alter_jobposting_application_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='resumevariant',
            name='source_pdf_path',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.CreateModel(
            name='CoverLetterVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField()),
                ('file_path', models.CharField(blank=True, max_length=512)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cover_letter_variants', to='applications.application')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cover_letter_variants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobDescriptionSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('extracted_text', models.TextField()),
                ('source_url', models.URLField(blank=True)),
                ('fetched_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('job_posting', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='description_snapshot', to='applications.jobposting')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
